// components/CurrentlyPlaying.vue
<template>
  <div class="column is-12 has-text-centered currently-playing">
    <img :src="imageUrl">
    <h5 class="is-size-5">{{ track.name }}</h5>
    <p v-if="track.artists">{{ track.artist_names.join(', ') }}</p>
    <p v-if="playing" class="is-size-7">matches: {{ matchingPlaylist }}</p>
  </div>
</template>

<script>
export default {
  computed: {
    playing() {
      return !this.$store.state.playbackState.paused
    },
    matchingPlaylist() {
      return this.$store.state.playlists.find(p => p.id === this.track.playlist_matches).name
    },
    imageUrl() {
      return this.track.album.images.max('height').url
    },
    track() {
      return this.$store.getters.currentTrack
    }
  }
}
</script>

<style scoped>
.currently-playing {
    height: 380px;
    min-height: 380px;
}

.currently-playing img {
    height: 280px;
}
</style>

// client/components/CurrentlyPlaying.tsx
import React from "react";

import { InboxTrack, Image } from "../../types";
import SelectMatchingPlaylist from "./SelectMatchingPlaylist";
import { maxBy } from "../../lib/util";

interface RichInboxTrack extends InboxTrack {
  album: {
    images: Image[];
  };
}

interface CurrentlyPlayingProps {
  track: RichInboxTrack;
}

export default function CurrentlyPlaying({ track }: CurrentlyPlayingProps) {
  const imageUrl = maxBy(track.album.images, "height").url;

  return (
    <div className="column is-12 has-text-centered currently-playing">
      <img src={imageUrl} style={{ height: "280px" }} />
      <h5 className="is-size-5 has-text-weight-semibold">{track.name}</h5>
      {track.artists && (
        <p className="has-text-weight-semibold">{track.artist_names.join(", ")} </p>
      )}
      {track.track_id && <SelectMatchingPlaylist track={track} />}
    </div>
  );
}
