// client/components/PlaylistRow.vue
<template>
  <tr>
    <td>
      <img :src="playlist.images.min('height').url" alt="" class="playlist-cover">
    </td>
    <td>{{ playlist.name }}</td>
    <td>
      <div class="select">
        <select @change="setPlaylistType">
          <option
            v-for="t in types"
            :key="t"
            :value="t"
            :selected="t === playlist.playlist_type">
            {{ t }}
          </option>
        </select>
      </div>
    </td>
  </tr>
</template>

<script>
export default {
  props: {
    playlist: {
      type: Object,
      default: () => {}
    }
  },
  data() {
    return { types: ['ignored', 'curated', 'inbox'] }
  },
  methods: {
    setPlaylistType(e) {
      this.$store.dispatch('setPlaylistType', { id: this.playlist.id, type: e.target.value })
    }
  }
}
</script>

<style scoped>
img.playlist-cover {
    max-height: 60px;
    height: 60px;
}
</style>

// client/components/PlaylistRow.tsx
import React from "react";

import { Playlist, PlaylistType } from "../../types";
import { useActions } from "../store";
import { minBy } from "../../lib/util";

interface PlaylistRowProps {
  playlist: Playlist;
}

export default function PlaylistRow({ playlist }: PlaylistRowProps) {
  const patchPlaylistType = useActions(actions => actions.playlists.patchPlaylistType);
  return (
    <tr>
      <td>
        <img src={minBy(playlist.images, "height").url} className="playlist-cover" />
      </td>
      <td className="playlist-name">{playlist.name}</td>
      <td>
        <div className="select">
          <select
            defaultValue={playlist.playlist_type}
            onChange={async e => {
              await patchPlaylistType({
                id: playlist.id,
                type: e.target.value as PlaylistType
              });
            }}
          >
            {Object.values(PlaylistType).map((pt: PlaylistType) => {
              return (
                <option key={pt} value={pt}>
                  {pt}
                </option>
              );
            })}
          </select>
        </div>
      </td>
    </tr>
  );
}
