// pages/playlists.vue
<template>
  <div class="columns is-centered">
    <div class="column is-narrow">
      <table class="table center-table">
        <thead>
          <tr>
            <th />
            <th>Name</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
          <PlaylistRow v-for="playlist in playlists" :key="playlist.id" :playlist="playlist"/>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import PlaylistRow from '~/components/PlaylistRow'
export default {
  components: {
    PlaylistRow
  },
  computed: {
    playlists() {
      return this.$store.state.playlists
    }
  }
}
</script>


<style scoped>
</style>

// client/components/Playlists.tsx
import React from "react";

import { useStore } from "../store";
import PlaylistRow from "./PlaylistRow";

export default function Playlists() {
  const playlists = useStore(state => state.playlists.playlists);
  return (
    <div className="columns is-centered">
      <div className="column is-narrow">
        <table className="table center-table">
          <thead>
            <tr>
              <th />
              <th>Name</th>
              <th>Type</th>
            </tr>
          </thead>
          <tbody>
            {playlists.map(p => {
              return <PlaylistRow key={p.id} playlist={p} />;
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
